### ISSUE TITLE
33J, 41J 셀에 대한 OCV-SOC table 및 capacity 측정 요청 (KETI, 인셀, 충남대)

### ISSUE THREAD

**Issue by coffeetumbler** [keti-dp/OpenESS#14]
안녕하세요.
서울대학교 연구원 정윤기입니다.

시온유, 판리 태양광 데이터의 OCV 라벨링을 위한 **OCV-SOC table** 및 **셀 capacity** 측정을 요청드립니다.

배터리 셀은 21700 33J와 41J 두 종류로
각각 min-max cut-off **3.0V/4.1V**, **0.2C-rate** CC-CV 충전 및 CC 방전 조건에서 (resting 최소 1시간)
SOC-OCV table (최소 5% 단위) 및 셀 capacity (Ah 단위) 측정을 요청드립니다.

감사합니다.

**Comment by cwkim** [comment]
메일 보내드린 것처럼, 인셀측에서는 완전한 신품 배터리는 단종되어 없으며 테스트만 거친(1사이클 이내) 배터리 확보 가능하다고 전달받았습니다. 아쉽지만 해당 시료라도 받을 수 있도록 일정을 조율 중에 있습니다.

**Comment by cwkim** [comment]
@JeonYoonChang 전윤창 전임님, 21700 33J와 41J 두가지 시료에 대해서 수령 가능한 일정 문의드립니다.

**Comment by cwkim** [comment]
@coffeetumbler ESS 배터리 21700 33J와 41J 시료는 9월 21일 인셀에서 종류별로 3개씩 확보 예정입니다. 이후 충남대에 전달할 예정입니다. 업무에 참고 부탁드립니다.

**Comment by cwkim** [comment]
@coffeetumbler ESS 배터리 21700 33J와 41J 시료는 예정대로 인셀에서 전달받아 충남대에 전달해드렸습니다. 충남대와 세부 일정 및 조건을 확인하여 진행하시면 됩니다.

**Comment by coffeetumbler** [comment]
@cwkim @Miyoung-Lee37 시료 전달된 사항을 확인했습니다. 배터리 셀 실험 일정이 잡히면 실험 예정일 및 진행 상황을 공유 부탁드립니다. 감사합니다.
