### ISSUE TITLE
안전AI Tracker 개발

### ISSUE THREAD

**Issue by cwkim** [keti-dp/OpenESS#4]
.

**Comment by cwkim** [comment]
@WoojungChoi @Surplus-Spec 각각 구현한 배터리 분석 S/W 모델에 대해 정리하여 PPT 장표 업로드 요청합니다.
1. 문제점/분석인사이트
2. 개선점/극복점
3. 주요 알고리즘 코드
4. 결과
5. 추가/수정 요소

위주로 장표 구성 요청

**Comment by cwkim** [comment]
@jwpark9010 : maintenance prediction 관련 주요 논문 조사 후 장표 업로드 요청

**Comment by Surplus-Spec** [comment]
[State_of_Health-Tracker.pdf](https://github.com/keti-dp/OpenESS/files/8021162/State_of_Health-Tracker.pdf)
State-of-Health 추정 알고리즘 정리입니다.

**Comment by Surplus-Spec** [comment]
[Max_Cell_Voltage-Tracker.pdf](https://github.com/keti-dp/OpenESS/files/8021164/Max_Cell_Voltage-Tracker.pdf)
Max Cell Voltage 예측 분석 정리입니다.

**Comment by WoojungChoi** [comment]
[랙별최대셀전압차이_안전트래커.pdf](https://github.com/keti-dp/OpenESS/files/8028791/_.pdf)
랙별 최대 셀 전압차이 선형 회귀모델을 이용한 안전트래커 정리입니다.

**Comment by jwpark9010** [comment]
maintenance prediction 관련 논문과 간략한 아키텍처 정리 내용입니다
[Predictive Maintenance 아키텍처.pptx](https://github.com/keti-dp/OpenESS/files/8037326/Predictive.Maintenance.pptx)
[A Survey of Predictive Maintenance; System, Purposes and Approaches.pdf](https://github.com/keti-dp/OpenESS/files/8037328/A.Survey.of.Predictive.Maintenance.System.Purposes.and.Approaches.pdf)
.

**Comment by cwkim** [comment]
TR 발생 전 셀 온도 편차를 통한 PdM 방법
= 단위시간 온도(C/min) - 현재 온도(C/min) 
= +- 0.2도 차이 발생
=> 평균 window 슬라이싱(경고1단계) + 기준값대비편차의 누적횟수(ex3초이상발생시)(경고2단계)

Ref: [A General Discussion of Li Ion Battery Safety](https://iopscience.iop.org/article/10.1149/2.F03122if/pdf)
