### ISSUE TITLE
ESS 위험 Level 개발

### ISSUE THREAD

**Issue by WoojungChoi** [keti-dp/OpenESS#6]
.

**Comment by WoojungChoi** [comment]
@Surplus-Spec 배터리 셀 Hazard Level 관련 논문 업로드 부탁드립니다.

**Comment by Surplus-Spec** [comment]
[Li-Ion Battery Fire Hazards and Safety Strategies.pdf](https://github.com/keti-dp/OpenESS/files/8038631/Li-Ion.Battery.Fire.Hazards.and.Safety.Strategies.pdf)
[A General Discussion of Li Ion Battery Safety.pdf](https://github.com/keti-dp/OpenESS/files/8038643/A.General.Discussion.of.Li.Ion.Battery.Safety.pdf)

배터리셀 Hazard level 관련 논문입니다.
